### ISSUE TITLE
Build fails for node 5.4.0

### ISSUE THREAD

**Issue by alexge233** [vincentsaluzzo/node-microphone#14]
Can't build on node 5.4.0, I get the following error:

```
AR(target) Release/obj.target/deps/lame/liblamevectorroutines.a
  COPY Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
In file included from ../src/bindings.cc:17:0:
/home/alex/.node-gyp/5.4.0/include/node/v8.h: In function ‘void nodelame::Initialize(v8::Handle<v8::Object>)’:
/home/alex/.node-gyp/5.4.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/bindings.cc:29:15: error: within this context
   HandleScope scope;
               ^
bindings.target.mk:105: recipe for target 'Release/obj.target/bindings/src/bindings.o' failed
make: *** [Release/obj.target/bindings/src/bindings.o] Error 1
make: Leaving directory '/home/alex/Projects/boombox/node_modules/lame/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-v5.4.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/node-v5.4.0-linux-x64/bin/node" "/usr/local/node-v5.4.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

**Comment by qmin80** [comment]
Same error on Node 4.4.1. 
I did 'npm install lame' and it worked, but npm install microphone has failed..

../deps/mpg123/src/libmpg123/layer3.c:1059:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1088:4: note: in expansion of macro ‘REFRESH_MASK’
    REFRESH_MASK;
    ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_arm.o
  AR(target) Release/obj.target/deps/mpg123/libmpg123.a
  COPY Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  AR(target) Release/obj.target/deps/lame/liblamevectorroutines.a
  COPY Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
In file included from ../src/bindings.cc:17:0:
/root/.node-gyp/4.4.1/include/node/v8.h: In function ‘void nodelame::Initialize(v8::Handlev8::Object)’:
/root/.node-gyp/4.4.1/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/bindings.cc:29:15: error: within this context
   HandleScope scope;
               ^
make: **\* [Release/obj.target/bindings/src/bindings.o] Error 1
make: Leaving directory `/home/odroid/Sandbox/mic/node-microphone/node_modules/lame/build'
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.96
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/odroid/Sandbox/mic/node-microphone/node_modules/lame
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! Linux 3.10.96
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! lame@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/odroid/Sandbox/mic/node-microphone/npm-debug.log

**Comment by qmin80** [comment]
Solution is here:
https://github.com/vincentsaluzzo/node-microphone/pull/12/files
